### ISSUE TITLE
Error in grunt serve

### ISSUE THREAD

**Issue by jjgonver** [Awk34/aksite#5]
I follow all the prerequisites and when I run grunt serve:

````
C:\Users\juanjo\aksite>grunt serve
Running "serve" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "env:all" (env) task

Running "injector:sass" (injector) task
Missing option `template`, using `dest` as template instead
Injecting scss files (33 files)
>> Nothing changed

Running "concurrent:server" (concurrent) task

    Running "newer:babel:client" (newer) task

    Running "babel:client" (babel) task

    Running "newer-postrun:babel:client:1:C:\Users\juanjo\aksite\node_modules\gr
unt-newer\.cache" (newer-postrun) task

    Done, without errors.


    Execution Time (2015-10-02 22:51:36 UTC)
    loading tasks       1.5s  ■■■■■■■■■■■■■ 29%
    newer:babel:client  1.5s  ■■■■■■■■■■■■ 28%
    babel:client        2.2s  ■■■■■■■■■■■■■■■■■■ 42%
    Total 5.2s

    Running "sass:server" (sass) task

    Done, without errors.


    Execution Time (2015-10-02 22:51:36 UTC)
    loading tasks  1.5s  ■■■■■■■■■■ 20%
    sass:server    6.3s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 80%
    Total 7.8s

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (64 files)
>> Nothing changed

Running "injector:sass" (injector) task
Missing option `template`, using `dest` as template instead
Injecting scss files (33 files)
>> Nothing changed

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
>> Nothing changed

Running "wiredep:client" (wiredep) task

Running "postcss:dist" (postcss) task
>> autoprefixer: C:\Users\client\bower_components\bourbon\app\assets\stylesheets
\css3\_flex-box.scss:72:4: You should write display: flex by final spec instead
of display: box
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
module.js:338
    throw err;
    ^
Error: Cannot find module './undefined.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:/Users/juanjo/aksite/server/config/environment/inde
x.js:86:5)
    at Module._compile (module.js:460:26)
    at normalLoader (C:\Users\juanjo\aksite\node_modules\babel-core\lib\api\regi
ster\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\juanjo\
aksite\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:/Users/juanjo/aksite/server/app.js:11:32)
    at Module._compile (module.js:460:26)
    at normalLoader (C:\Users\juanjo\aksite\node_modules\babel-core\lib\api\regi
ster\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\juanjo\
aksite\node_modules\babel-core\lib\api\register\node.js:216:7)
Stopping Express server

Running "wait" task
>> Waiting for server reload...
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
````

**Comment by Awk34** [comment]
That's strange. It should be setting `process.env.NODE_ENV` to 'development`. Try running `NODE_ENV=development grunt serve`.

**Comment by jjgonver** [comment]
That is! Now it works.
In windows:
````
set node_env=development
grunt serve
````
Thanks.

**Comment by Awk34** [comment]
No problem. It *should* default to `development`, but whatever...
